### ISSUE TITLE
sidebar not finding tasks

### ISSUE THREAD

**Issue by kildarr** [spmeesseman/vscode-taskexplorer#106] opened 2020-06-26 13:22 UTC
VsCode v.1.46.1(system setup)
TE v. 1.26.3

Sidebar never stops polling and never populates.  Task execution from hotkeys works fine.

**Comment by spmeesseman** [comment] 2020-09-26 15:14
cant seem to reproduce this.  do you have the Explorer View turned on as well?  Or just the SideBar view?

**Comment by dsalexander** [comment] 2020-10-11 16:34
@spmeesseman I've just started using Task Explorer (very nice so far!) and I've noticed that it doesn't find tasks that are installed globally for the User (e.g., ~/Library/Application Support/Code - Insiders/User/tasks.json). Is this by design?

**Comment by tkambler** [comment] 2020-12-13 16:23
I'm also running into this, FYI. It's a remote workspace.

**Comment by tkambler** [comment] 2020-12-13 17:23
I'm using [rush](https://rushjs.io/) to manage a monorepo. The cloned repository has a `common` folder at its root where various pnpm dependencies are managed. From what I've gathered so far, task explorer is finding 100's of errors in this folder, and reporting them to the _Problems_ console. It doesn't display tasks until this process finishes.

I have added this folder to task explorer's list of excluded folders, but it seems to have had no effect.

```
    "taskExplorer.exclude": [
      "**/.vscode-test/**",
      "**/bin/**",
      "**/build/**",
      "**/CompiledOutput/**",
      "**/dist/**",
      "**/doc/**",
      "**/ext/**",
      "**/out/**",
      "**/output/**",
      "**/packages/**",
      "**/release/**",
      "**/releases/**",
      "**/samples/**",
      "**/sdks/**",
      "**/static/**",
      "**/target/**",
      "**/test/**",
      "**/third_party/**",
      "**/vendor/**",
      "**/node_modules/**",
      "**/common/**",
      "**/temp/**",
    ],
![Screen Shot 2020-12-13 at 11 17 25 AM](https://user-images.githubusercontent.com/4448053/102018853-83e02d00-3d35-11eb-8176-79019d6b75dd.jpg)

```

**Comment by tkambler** [comment] 2020-12-13 17:56
Update:

Adding this to the project settings has resolved the problems panel issue, but it still takes several minutes for task explorer to display the tasks:

```
  "files.exclude": {
    "common/temp": true
  },
```

It appears that task explorer is ignoring our configuring that says to ignore grunt, gulp, appPublisher, etc...?
![Uploading Screen Shot 2020-12-13 at 11.55.41 AM.jpg…]()

**Comment by spmeesseman** [comment] 2021-02-06 20:26
> @spmeesseman I've just started using Task Explorer (very nice so far!) and I've noticed that it doesn't find tasks that are installed globally for the User (e.g., ~/Library/Application Support/Code - Insiders/User/tasks.json). Is this by design?

fixed in 1.29

**Comment by spmeesseman** [comment] 2021-02-06 20:31
npm tasks are provided by VSCode itself, so yeah, to ignore a path, you need to add the ignore path to VSCode setting, not Task Explorer, as you have found.  Task Explorer also doesnt have an ignore option for NPM, that is also managed by VSCode itself.

**Closed by spmeesseman** 2021-02-06 20:31 UTC
Labels: bug, todo

**Comment by spmeesseman** [comment] 2021-02-06 20:33
maybe a setting can be added to "ignore" npm tasks, but essentially this is the same as turning off npm task provider in VSCode, hmmm well maybe not, cause then the tasks are still available in the cmd apllete.  if you think an option to "ignore" npm tasks would be useful, please open another ticket as a featire request
